// Compiled by ClojureScript 1.10.339 {:static-fns true, :optimize-constants true}
goog.provide('value_prop.hoplon');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('hoplon.core');
goog.require('color.data');
value_prop.hoplon.value_prop = (function value_prop$hoplon$value_prop(){
return cljs.core.PersistentVector.fromArray([(function (){var G__10639 = cljs.core.cst$kw$css;
var G__10640 = new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$white_DASH_space,"nowrap"], null);
var G__10641 = "NearSeed";
return (hoplon.core.h1.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.h1.cljs$core$IFn$_invoke$arity$3(G__10639,G__10640,G__10641) : hoplon.core.h1.call(null,G__10639,G__10640,G__10641));
})(),(function (){var G__10642 = "Near: easy, journey.";
var G__10643 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10644 = "Seed: life, growth.";
var G__10645 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10646 = "NearSeed: together, potential.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$5 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$5(G__10642,G__10643,G__10644,G__10645,G__10646) : hoplon.core.p.call(null,G__10642,G__10643,G__10644,G__10645,G__10646));
})(),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("The story") : hoplon.core.h2.call(null,"The story")),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("One day, stuck doing something onerous, Dave (consultant, founder) flipped the table.") : hoplon.core.p.call(null,"One day, stuck doing something onerous, Dave (consultant, founder) flipped the table.")),(function (){var G__10647 = cljs.core.cst$kw$css;
var G__10648 = new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$color,color.data.accent], null);
var G__10649 = "(\u30CE\u0CA0\u76CA\u0CA0)\u30CE\u5F61\u253B\u2501\u253B";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10647,G__10648,G__10649) : hoplon.core.p.call(null,G__10647,G__10648,G__10649));
})(),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("\"Why is this difficult!?") : hoplon.core.p.call(null,"\"Why is this difficult!?")),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("\"The freelance lifestyle (and money) is great\u2026 until the chores pile up\u2026 tracking billables, chasing bureaucrats, presenting well, and diarising events\u2026") : hoplon.core.p.call(null,"\"The freelance lifestyle (and money) is great\u2026 until the chores pile up\u2026 tracking billables, chasing bureaucrats, presenting well, and diarising events\u2026")),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("\"Sure, there are cloud tools, integrations and service providers. Researching, configuring then maintaining them all takes hours \uD83D\uDE13") : hoplon.core.p.call(null,"\"Sure, there are cloud tools, integrations and service providers. Researching, configuring then maintaining them all takes hours \uD83D\uDE13")),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("\"Even after I am set up, should I be doing this? Chores aren't my passion. I'll wind up with mistakes and pointless fees. Working all the time, bumbling through\u2026 \uD83E\uDD14") : hoplon.core.p.call(null,"\"Even after I am set up, should I be doing this? Chores aren't my passion. I'll wind up with mistakes and pointless fees. Working all the time, bumbling through\u2026 \uD83E\uDD14")),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("\"I need to spend all my work time doing what I do best and none of my play time with chores on the mind.") : hoplon.core.p.call(null,"\"I need to spend all my work time doing what I do best and none of my play time with chores on the mind.")),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("And so he set out to create a system.") : hoplon.core.p.call(null,"And so he set out to create a system.")),(function (){var G__10650 = typography.hoplon.highlight.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["If this story resonates then keep reading.",(hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null))], 0));
var G__10651 = typography.hoplon.highlight.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["The system is waiting to support you."], 0));
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$2 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$2(G__10650,G__10651) : hoplon.core.p.call(null,G__10650,G__10651));
})(),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("The promise") : hoplon.core.h2.call(null,"The promise")),(function (){var G__10652 = cljs.core.map.cljs$core$IFn$_invoke$arity$2(hoplon.core.li,new cljs.core.PersistentVector(null, 11, 5, cljs.core.PersistentVector.EMPTY_NODE, ["Unlock time. Be awesome. Live the dream.","Be supported. Keep being you.","Strengthen existing relationships.","No bureaucrats. No bosses. No jobs. No recruiters.","Meet interesting people.","Transparency at every step.","Simple tools to help calibrate your trajectory.","Access vetted service providers.","Access services typically off-limits to individuals.","Build much more wealth than the $$$ value.","Unify it all under a single tax-deductible fee."], null));
return (hoplon.core.ul.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.ul.cljs$core$IFn$_invoke$arity$1(G__10652) : hoplon.core.ul.call(null,G__10652));
})(),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("The system") : hoplon.core.h2.call(null,"The system")),(function (){var G__10653 = typography.hoplon.highlight.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["NearSeed gives simplicity and context to everyday life."], 0));
var G__10654 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10655 = (hoplon.core.em.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.em.cljs$core$IFn$_invoke$arity$1("Almost") : hoplon.core.em.call(null,"Almost"));
var G__10656 = " too simple.";
var G__10657 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10658 = (hoplon.core.em.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.em.cljs$core$IFn$_invoke$arity$1("Just enough") : hoplon.core.em.call(null,"Just enough"));
var G__10659 = " context.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$7 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$7(G__10653,G__10654,G__10655,G__10656,G__10657,G__10658,G__10659) : hoplon.core.p.call(null,G__10653,G__10654,G__10655,G__10656,G__10657,G__10658,G__10659));
})(),(function (){var G__10660 = "The system is divided into 4 thematic tiers.";
var G__10661 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10662 = "Access to each tier is tied to your professional experience and income.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10660,G__10661,G__10662) : hoplon.core.p.call(null,G__10660,G__10661,G__10662));
})(),(function (){var G__10663 = "Each tier gives monthly credits.";
var G__10664 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10665 = "Credits can be exchanged for services aligned with the theme of your current tier.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10663,G__10664,G__10665) : hoplon.core.p.call(null,G__10663,G__10664,G__10665));
})(),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("A dedicated NearSeed helper will review your situation periodically and recommend the best services for you.") : hoplon.core.p.call(null,"A dedicated NearSeed helper will review your situation periodically and recommend the best services for you.")),(function (){var G__10666 = "The first tiers focus on focus and stability.";
var G__10667 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10668 = "Accounting, tools & calculators, goal tracking, diarising, and task management.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10666,G__10667,G__10668) : hoplon.core.p.call(null,G__10666,G__10667,G__10668));
})(),(function (){var G__10669 = "Later tiers build on the foundations of earlier tiers.";
var G__10670 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10671 = "Global travel, public speaking, and more sophisticated opportunities.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10669,G__10670,G__10671) : hoplon.core.p.call(null,G__10669,G__10670,G__10671));
})(),(hoplon.core.h2.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h2.cljs$core$IFn$_invoke$arity$1("The tiers") : hoplon.core.h2.call(null,"The tiers")),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("0: Automation") : hoplon.core.h3.call(null,"0: Automation")),(function (){var G__10672 = typography.hoplon.highlight.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Start ",(hoplon.core.em.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.em.cljs$core$IFn$_invoke$arity$1("those") : hoplon.core.em.call(null,"those"))," conversations with yourself."], 0));
return (hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1(G__10672) : hoplon.core.h3.call(null,G__10672));
})(),(function (){var G__10673 = "Cloud platform for social, self & wealth development.";
var G__10674 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10675 = "$50 p.m. for everyone.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10673,G__10674,G__10675) : hoplon.core.p.call(null,G__10673,G__10674,G__10675));
})(),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("A: Accountability") : hoplon.core.h3.call(null,"A: Accountability")),(function (){var G__10676 = typography.hoplon.highlight.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Unlock time for growth."], 0));
return (hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1(G__10676) : hoplon.core.h3.call(null,G__10676));
})(),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("Everything in 0: Automation and credits for\u2026") : hoplon.core.p.call(null,"Everything in 0: Automation and credits for\u2026")),(function (){var G__10677 = "Personal accountability, daily grind assistance, bookkeeping and accounting.";
var G__10678 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10679 = "$100 p.w. for anyone with 5+ years industry experience.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10677,G__10678,G__10679) : hoplon.core.p.call(null,G__10677,G__10678,G__10679));
})(),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("AA: Activation") : hoplon.core.h3.call(null,"AA: Activation")),(function (){var G__10680 = typography.hoplon.highlight.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Present well to become known for ideas."], 0));
return (hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1(G__10680) : hoplon.core.h3.call(null,G__10680));
})(),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("Everything in A: Accountability and credits for\u2026") : hoplon.core.p.call(null,"Everything in A: Accountability and credits for\u2026")),(function (){var G__10681 = "Personal branding, travel and social opportunities.";
var G__10682 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10683 = "$200 p.w. for anyone earning $150k+.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10681,G__10682,G__10683) : hoplon.core.p.call(null,G__10681,G__10682,G__10683));
})(),(hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1("AAA: Access") : hoplon.core.h3.call(null,"AAA: Access")),(function (){var G__10684 = typography.hoplon.highlight.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2(["Reach your potential."], 0));
return (hoplon.core.h3.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.h3.cljs$core$IFn$_invoke$arity$1(G__10684) : hoplon.core.h3.call(null,G__10684));
})(),(hoplon.core.p.cljs$core$IFn$_invoke$arity$1 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$1("Everything in AA: Activation and credits for\u2026") : hoplon.core.p.call(null,"Everything in AA: Activation and credits for\u2026")),(function (){var G__10685 = "Exclusive co-working spaces, events and co-founder/VC opportunities.";
var G__10686 = (hoplon.core.br.cljs$core$IFn$_invoke$arity$0 ? hoplon.core.br.cljs$core$IFn$_invoke$arity$0() : hoplon.core.br.call(null));
var G__10687 = "$300 p.w. for anyone earning $180k+.";
return (hoplon.core.p.cljs$core$IFn$_invoke$arity$3 ? hoplon.core.p.cljs$core$IFn$_invoke$arity$3(G__10685,G__10686,G__10687) : hoplon.core.p.call(null,G__10685,G__10686,G__10687));
})()], true);
});
